<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import api from '../services/api'
import type { Person } from '../types'
const route = useRoute(); const router = useRouter(); const person = ref<Person | null>(null); const password = ref(''); const error = ref(''); const result = ref(''); const saving = ref(false)
const shareUrl = computed(() => person.value?.qrShareToken ? `${import.meta.env.VITE_PUBLIC_API_BASE_URL || window.location.origin}/public/visitor-qr/${person.value.qrShareToken}` : '')
function local(value?: string) { return value ? new Date(value).toISOString().slice(0, 16) : '' }
async function load() { person.value = (await api.get<Person>(`/visitors/${route.params.id}`)).data; if (person.value) { person.value.cardNo = person.value.cardNos?.join(', ') || person.value.cardNo; person.value.enableBeginTimeUtc = local(person.value.enableBeginTimeUtc); person.value.enableEndTimeUtc = local(person.value.enableEndTimeUtc) } }
async function save() { if (!person.value) return; saving.value = true; error.value = ''; try { const r = await api.put(`/visitors/${person.value.id}`, { name: person.value.name, cardNo: person.value.cardNo || null, password: password.value || null, faceAssetId: person.value.faceAssetId || null, generateQr: Boolean(person.value.qrShareToken), enableBeginTimeUtc: new Date(person.value.enableBeginTimeUtc!).toISOString(), enableEndTimeUtc: new Date(person.value.enableEndTimeUtc!).toISOString() }); result.value = JSON.stringify(r.data); password.value = ''; await load() } catch (e:any) { error.value = e.response?.data || e.message } finally { saving.value = false } }
async function reissue() { if (!person.value) return; const { data } = await api.post(`/visitors/${person.value.id}/reissue`, { password: password.value || null }); result.value = JSON.stringify(data); password.value = ''; await load() }
async function revoke() { if (!person.value) return; await api.post(`/visitors/${person.value.id}/revoke-qr`); await load() }
onMounted(load)
</script>
<template><a-page-header title="访客详情" @back="router.push('/visitors')" /><a-card v-if="person" style="max-width:760px"><a-alert v-if="error" type="error" :message="error" show-icon style="margin-bottom:16px" /><a-form layout="vertical"><a-form-item label="姓名"><a-input v-model:value="person.name" /></a-form-item><a-row :gutter="16"><a-col :span="12"><a-form-item label="开始时间"><a-input v-model:value="person.enableBeginTimeUtc" type="datetime-local" /></a-form-item></a-col><a-col :span="12"><a-form-item label="结束时间"><a-input v-model:value="person.enableEndTimeUtc" type="datetime-local" /></a-form-item></a-col></a-row><a-form-item label="卡号（可多张，以逗号或换行分隔）"><a-textarea v-model:value="person.cardNo" /></a-form-item><a-form-item label="密码（仅本次下发）"><a-input-password v-model:value="password" /></a-form-item><a-space><a-button type="primary" :loading="saving" @click="save">保存并重新下发</a-button><a-button @click="reissue">仅重新下发</a-button><a-button v-if="person.qrShareToken" danger @click="revoke">撤销二维码</a-button></a-space></a-form><a-divider /><a-descriptions bordered :column="1"><a-descriptions-item label="设备人员编号">{{ person.deviceEmployeeNo || '-' }}</a-descriptions-item><a-descriptions-item label="二维码外链">{{ shareUrl || '未生成或已撤销' }}</a-descriptions-item></a-descriptions><pre v-if="result" style="margin-top:16px;white-space:pre-wrap">{{ result }}</pre></a-card></template>
