// <auto-generated />
using System;
using AccessIt.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccessIt.Api.Data.Migrations
{
    [DbContext(typeof(AccessItDbContext))]
    [Migration("20260623133054_AddAllDayTemplateId")]
    partial class AddAllDayTemplateId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("AccessIt.Api.Domain.AccessCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccessPersonId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CardNo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long?>("HikiotIdentificationId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVirtual")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccessPersonId");

                    b.HasIndex("CardNo")
                        .IsUnique();

                    b.ToTable("AccessCards");
                });

            modelBuilder.Entity("AccessIt.Api.Domain.AccessDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("AllDayTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceSerial")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupNo")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasAllDayTemplate")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsManaged")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SupportsCardInfo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsFace")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsPassword")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsPurePassword")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsRemoteOpen")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsUserInfo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsUserRightPlanTemplate")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeviceSerial")
                        .IsUnique();

                    b.ToTable("AccessDevices");
                });

            modelBuilder.Entity("AccessIt.Api.Domain.AccessPerson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DingTalkUserId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeNo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EnableBeginTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EnableEndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("HikiotDepartmentNo")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long?>("HikiotFaceIdentificationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HikiotJobNumber")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("HikiotJobPosition")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("HikiotPersonNo")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int?>("HikiotSex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxOpenDoorTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mobile")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PermanentValid")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeNo")
                        .IsUnique();

                    b.HasIndex("HikiotPersonNo")
                        .IsUnique()
                        .HasFilter("\"HikiotPersonNo\" IS NOT NULL");

                    b.ToTable("AccessPeople");
                });

            modelBuilder.Entity("AccessIt.Api.Domain.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DingTalkOpenId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DingTalkUnionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DingTalkUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastDirectorySyncAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mobile")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DingTalkUnionId")
                        .IsUnique()
                        .HasFilter("\"DingTalkUnionId\" IS NOT NULL");

                    b.HasIndex("DingTalkUserId")
                        .IsUnique();

                    b.ToTable("ApplicationUsers");
                });

            modelBuilder.Entity("AccessIt.Api.Domain.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc", "Action");

                    b.ToTable("AuditEvents");
                });

            modelBuilder.Entity("AccessIt.Api.Domain.DeviceGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccessDeviceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccessPersonId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("HikiotAuthorityConfigId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HikiotInfoStatus")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HikiotIsSending")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HikiotIsSupported")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HikiotIssueBatchNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("HikiotLastFailedReason")
                        .HasColumnType("TEXT");

                    b.Property<long?>("HikiotPersonDeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("HikiotStatusCheckedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccessDeviceId");

                    b.HasIndex("AccessPersonId", "AccessDeviceId")
                        .IsUnique();

                    b.ToTable("DeviceGrants");
                });

            modelBuilder.Entity("AccessIt.Api.Domain.DevicePassword", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccessPersonId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtectedValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccessPersonId")
                        .IsUnique();

                    b.ToTable("DevicePasswords");
                });

            modelBuilder.Entity("AccessIt.Api.Domain.FaceAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccessPersonId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ByteLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("HikiotIdentificationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PublicToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccessPersonId");

                    b.HasIndex("PublicToken")
                        .IsUnique();

                    b.ToTable("FaceAssets");
                });

            modelBuilder.Entity("AccessIt.Api.Domain.HikiotAuthorizationState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("State")
                        .IsUnique();

                    b.ToTable("HikiotAuthorizationStates");
                });

            modelBuilder.Entity("AccessIt.Api.Domain.HikiotConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountNo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AppTokenExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AuthorizedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorizedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultDepartmentNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastErrorAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NeedsReauthorization")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProtectedAppAccessToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtectedRefreshAppToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtectedRefreshUserToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtectedUserAccessToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamNo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UserTokenExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HikiotConnections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NeedsReauthorization = true
                        });
                });

            modelBuilder.Entity("AccessIt.Api.Domain.HikiotIssueBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccessPersonId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BatchNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CheckedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceSerial")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BatchNo")
                        .IsUnique();

                    b.HasIndex("AccessPersonId", "CreatedAtUtc");

                    b.ToTable("HikiotIssueBatches");
                });

            modelBuilder.Entity("AccessIt.Api.Domain.IssuanceJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AccessDeviceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AccessPersonId")
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CardNoOverride")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NextAttemptAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentJobId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TraceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Status", "NextAttemptAtUtc");

                    b.ToTable("IssuanceJobs");
                });

            modelBuilder.Entity("AccessIt.Api.Domain.PersonNumberSequence", b =>
                {
                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastValue")
                        .HasColumnType("INTEGER");

                    b.HasKey("Kind");

                    b.ToTable("PersonNumberSequences");
                });

            modelBuilder.Entity("AccessIt.Api.Domain.SyncConflict", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AccessPersonId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("Resolution")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolvedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SyncRunId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SyncRunId", "Resolution");

                    b.ToTable("SyncConflicts");
                });

            modelBuilder.Entity("AccessIt.Api.Domain.SyncRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccessDeviceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConflictCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FailureMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("NewCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RemoteCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("StartedByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SyncRuns");
                });

            modelBuilder.Entity("AccessIt.Api.Domain.VisitorQrShare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccessPersonId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("IssuedToHostUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpaqueToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QrCodeContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("OpaqueToken")
                        .IsUnique();

                    b.ToTable("VisitorQrShares");
                });

            modelBuilder.Entity("AccessIt.Api.Domain.AccessCard", b =>
                {
                    b.HasOne("AccessIt.Api.Domain.AccessPerson", "AccessPerson")
                        .WithMany("Cards")
                        .HasForeignKey("AccessPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessPerson");
                });

            modelBuilder.Entity("AccessIt.Api.Domain.DeviceGrant", b =>
                {
                    b.HasOne("AccessIt.Api.Domain.AccessDevice", "AccessDevice")
                        .WithMany("DeviceGrants")
                        .HasForeignKey("AccessDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccessIt.Api.Domain.AccessPerson", "AccessPerson")
                        .WithMany("DeviceGrants")
                        .HasForeignKey("AccessPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessDevice");

                    b.Navigation("AccessPerson");
                });

            modelBuilder.Entity("AccessIt.Api.Domain.DevicePassword", b =>
                {
                    b.HasOne("AccessIt.Api.Domain.AccessPerson", "AccessPerson")
                        .WithOne()
                        .HasForeignKey("AccessIt.Api.Domain.DevicePassword", "AccessPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessPerson");
                });

            modelBuilder.Entity("AccessIt.Api.Domain.FaceAsset", b =>
                {
                    b.HasOne("AccessIt.Api.Domain.AccessPerson", "AccessPerson")
                        .WithMany("FaceAssets")
                        .HasForeignKey("AccessPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessPerson");
                });

            modelBuilder.Entity("AccessIt.Api.Domain.AccessDevice", b =>
                {
                    b.Navigation("DeviceGrants");
                });

            modelBuilder.Entity("AccessIt.Api.Domain.AccessPerson", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("DeviceGrants");

                    b.Navigation("FaceAssets");
                });
#pragma warning restore 612, 618
        }
    }
}
