// <auto-generated />
using System;
using AccessIt.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccessIt.Api.Migrations
{
    [DbContext(typeof(AccessItDbContext))]
    [Migration("20260624125553_InitialAccessIt")]
    partial class InitialAccessIt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("AccessIt.Api.Domain.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DingTalkOpenId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DingTalkUnionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DingTalkUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastDirectorySyncAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mobile")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DingTalkUnionId")
                        .IsUnique()
                        .HasFilter("\"DingTalkUnionId\" IS NOT NULL");

                    b.HasIndex("DingTalkUserId")
                        .IsUnique();

                    b.ToTable("ApplicationUsers");
                });

            modelBuilder.Entity("AccessIt.Api.Domain.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc", "Action");

                    b.ToTable("AuditEvents");
                });

            modelBuilder.Entity("AccessIt.Api.Domain.HikiotAuthorizationState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("State")
                        .IsUnique();

                    b.ToTable("HikiotAuthorizationStates");
                });

            modelBuilder.Entity("AccessIt.Api.Domain.HikiotConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountNo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AppTokenExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AuthorizedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorizedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultDepartmentNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastErrorAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NeedsReauthorization")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProtectedAppAccessToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtectedRefreshAppToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtectedRefreshUserToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtectedUserAccessToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamNo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UserTokenExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HikiotConnections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NeedsReauthorization = true
                        });
                });

            modelBuilder.Entity("AccessIt.Api.Services.FaceAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("ByteLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PublicToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PublicToken")
                        .IsUnique();

                    b.ToTable("FaceAssets");
                });
#pragma warning restore 612, 618
        }
    }
}
